### PR TITLE
Replaced ol/PluggableMap with ol/Map in definition file.

### PR DESCRIPTION
**Pull request by adhaca**
#489

### CODE REVIEW

**Comment by walkermatt** [comment]
@adhaca thanks, if you install the dev dependencies and run `npm run build` then the types and readme will be automatically updated.

**Comment by adhaca** [comment]
@walkermatt Thanks for the reply. I installed ol-layerswitcher as both a dependency and a devDependency. But unless I'm missing something I don't see any changes in the definition file. There is still an import statement for PluggableMap in the [latest version.](https://github.com/walkermatt/ol-layerswitcher/blob/master/dist/ol-layerswitcher.d.ts)

**Comment by walkermatt** [comment]
Sorry, I wasn't clear.

Within your local clone of the ol-layerswitcher repository, install the dev dependencies and run `npm run build` then the types and readme will be automatically updated.

**Comment by adhaca** [comment]
I already ran a `npm install` and a `npm run build` on my local clone (2nd commit). Only forgot to update readme.

**Comment by walkermatt** [comment]
Merged in [46cfb40](https://github.com/walkermatt/ol-layerswitcher/commit/46cfb40ce6e2f78a74ff7bf9c5d310c02374d7c1) :tada:

**Pull request closed without merging**
