### PR TITLE
Merge and enhance group checkboxes.

### PR DESCRIPTION
**Pull request by dbrnz**

### CODE REVIEW

**Comment by walkermatt** [comment]
@dbrnz can you post a link to an example?

**Comment by dbrnz** [comment]
@walkermatt, there is an example at https://raw.githack.com/dbrnz/ol-layerswitcher/7b8c41d/examples/select-groups.html

**Comment by umbe1987** [comment]
Seems cool! Just few observations if I can:

- one can actually turn off the basemaps now.
- when the user switches basemap for the first time, the checkbox becomes a little square, instead of the usual tick symbol

I guess it would be better to remove this functionality for the basemaps, what do you @dbrnz and @walkermatt think?

@dbrnz thanks for the PR and @walkermatt thanks for considering my observations.

**Comment by dbrnz** [comment]
Thanks @umbe1987 for the review! I'll remove the basemap functionality and also improve detection of the indeterminate state for parents of nested groups.

**Comment by walkermatt** [comment]
The functionality looks good :+1:

My thoughts:

### Basemaps

I feel that basemap groups shouldn't have a checkbox to allow hiding all basemaps. If a user wants to provide a "blank basemap" option they can do so by defining a blank layer ([for instance see openlayers/openlayers#4103](https://github.com/openlayers/openlayers/issues/4103)) in a basemap group.

### Collapsible groups

I'd prefer the toggle icon to be first, then the checkbox and the label.

**Comment by dbrnz** [comment]
@walkermatt, agree 100% regarding basemaps.

The toggle icon though is implemented in CSS by applying a style to the label, so the two are inseparable. We could though have checkboxes after their labels, say in a flush right column, although IMHO this is a styling issue -- can default label placement be overridden using CSS??

**Comment by walkermatt** [comment]
@dbrnz it might be possible to position the toggle icon before the checkbox via CSS.

Try something funky like:

```css
.layer-switcher .group.layer-switcher-fold > label::before{
    margin-right:30px;
    margin-left:-35px;
}
```

**Comment by dbrnz** [comment]
Thanks @walkermatt, this does the job, although I personally prefer having the checkboxes vertically aligned. What about having something in the documentation telling users how to style the control?

screen shot 2019-02-13 at 8 56 01 pmscreen shot 2019-02-13 at 8 56 47 pm

**Comment by dbrnz** [comment]
Oops, spoke too soon, here's the other option:

screen shot 2019-02-13 at 9 06 27 pmscreen shot 2019-02-13 at 9 05 43 pm

Maybe what I was trying to say is that I prefer to keep the checkboxes and the toggle+label as separate vertical visual elements, and having a checkbox come between a toggle and label breaks this.

Regardless, this doesn't affect functionality, and I'm happy to go with your preferred style knowing that it can easily be overridden.

**Comment by umbe1987** [comment]
@dbrnz Don't know if your example (provided above) is updated, but I just noticed that the little square in the checkbox does not always work correctly.

Example:
- start the example where all layers are turned on.
- turn off layer Wards in the Census group -> Census group checkbox becomes a little square (correct)
- turn off all layers by turning off the main Overlays group
- turn on again the main Overlays group -> Census group is still a little square (wrong) rather than a tick
immagine

**Comment by dbrnz** [comment]
Thanks @umbe1987 I had spotted this -- it's what I meant by "improve detection of the indeterminate state for parents of nested groups" above.

**Comment by dbrnz** [comment]
@walkermatt , @umbe1987 this should be [ready to go](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/select-groups.html).

**Comment by walkermatt** [comment]
@dbrnz looking good, thanks for your work on this.

The only outstanding issue I've spotted is that there is a gap between the fold toggle and group label when the base group is folded. The issue can be see in the [sidebar example](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/sidebar.html).

Could probably be resolved by adding a class to the base `li` something like `layer-switcher-basegroup` and some corresponding CSS.

**Comment by dbrnz** [comment]
@walkermatt, how does [this](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/sidebar.html) look??

**Comment by walkermatt** [comment]
@dbrnz looks good, anymore changes you'd like to make?

I'd like to propose the following minor CSS tweaks:

```diff
.layer-switcher .group.layer-switcher-fold > label::before{
-  margin-right:22px;
-  margin-left:-29px;
-  margin-bottom:1px;
+  margin-right:24px;
+  margin-left:-31px;
+  margin-bottom:3px;
}

.layer-switcher .group.layer-switcher-fold.layer-switcher-open > label::before{
-  margin-right:21px;
-  margin-left:-28px;
+  margin-right:24px;
+  margin-left:-31px;
}
```

Once you're happy we can test in IE, Edge, FF and Chrome between us :+1:

**Comment by dbrnz** [comment]
@walkermatt I've made your suggested CSS tweaks. All looks good to me in Safari, Chrome, Firefox and Edge.

IE 11 though has the layerswitcher menu disappear when the mouse hovers over it, plus it gets a Javascript error as it doesn't support the `startswith()` method on a string. How important is IE 11 compatibility, given that it is now less than 11 months before MS drop support and they advise upgrading to Edge?

**Comment by umbe1987** [comment]
Sorry to jump in again this suddenly, but I still noticed the "indeterminate state for parents of nested groups" thing as I mentioned before. @dbrnz Are you still working on this? Anyway, thanks for the great work!

**Comment by dbrnz** [comment]
@umbe1987 thanks for checking again! Obviously I've missed some cases (and interesting, when the wrong state is displayed things come right if the switcher is closed and reopened, and sometimes the correct display goes wrong after reopening...).

@walkermatt I'll get this resolved later on in the week.

**Comment by dbrnz** [comment]
@walkermatt and @umbe1987, over to you to [verify I haven't overlooked anything else](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/select-groups.html)... Thanks.

**Comment by umbe1987** [comment]
Not a real issue, but I noticed that:

1. If I switch off "Wards" and then click on "Overlays", everything turn on
2. If I switch off "Census" and then click on "Overlays", everything turn off

So, it seems there's an opposite behaviour of turning on/off the layers if something happened to a child element or to a child of a child element.
I mean, not really a big deal, but I guess this behaviour should be consistent across the hierarchy.

Another small detail: if I click on the label of an element, the click turns that element on or off, except if it is a group, where the click triggers the expands/shrink the sublayers list instead of changing its visibility.

**Comment by walkermatt** [comment]
@umbe1987 @dbrnz I agree with the comment regarding group toggle behavior. I think the default behavior should be: if a group checkbox is in the indeterminate state then clicking on it will toggle all children **on** as per this [Three state checkbox example](https://dhtmlx.com/docs/products/dhtmlxTree/samples/02_checkboxes/05_tree_checkboxes.html).

**Comment by dbrnz** [comment]
@walkermatt thanks for clarifying what should happen when an indeterminate checkbox is clicked. All should now be (finally!) good to go.

**Comment by swalterfub** [comment]
Sorry for jumping in that late, but I like the behaviour of the [two-state case](https://dhtmlx.com/docs/products/dhtmlxTree/samples/02_checkboxes/05_tree_checkboxes.html). In my case, I have dozens of sublayers which I want to temporarily disable, but I want to be able to keep my selection of sublayers. As far as I understand, in your implementation, all sublayers are activated once I re-activate the parent group (and the specific selection of sub-layers is lost). Am I right? Or is it possible to choose between two-state and three-state? For example, Google Earth uses three-state, while ArcGIS uses two-state behaviour.

**Comment by dbrnz** [comment]
Hmm, this sounds like it should be an option. @walkermatt, what do you think would be a suitable name and values for a new option?

**Comment by umbe1987** [comment]
Just a suggestion: what about keeping the behaviour of the indeterminate checkbox as is and add an option to choose whether it shoul be three or two state checbox in another PR as enhancement? Otherwise there would be too much work within a single PR.
However, I do like the two state as @swalterfub, so I'd be happy to contribute or help if this is merged. Just my two cents though.

**Comment by umbe1987** [comment]
@walkermatt any chance this PR will get merged anytime soon?

**Comment by walkermatt** [comment]
I'm planning on picking this backup. I've had a look this afternoon and I think we need to improve the folding. I'm thinking of creating actual buttons for folding/ unfolding groups instead of the CSS approach which is fiddly and not great for accessibility. I'll have a tinker and report back sometime next week.

**Comment by walkermatt** [comment]
I've had some time today on the train to have a look at this. I've just pushed my changes to the [selectable-groups branch of dbrnz/ol-layerswitcher](https://github.com/dbrnz/ol-layerswitcher/tree/selectable-groups). The example can be tested here: https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/select-groups.html

Testing on Firefox looks like I need to tweak the CSS for the fold buttons but I think the logic for folding and selectable groups is working as expected. Feedback welcome.

**Comment by umbe1987** [comment]
Looking great and working fine also on Chrome mobile. Will test on desktop soon. Thanks both for the nice job!

**Comment by swalterfub** [comment]
Looks good to me, too! I like the animated arrows...

As a side note, as I already said, I'm more in favor of the two-state case as mentioned above. In my case, I can have dozens of layers under one group, and I don't want to loose their state of being  selected or not when I disable/re-enable the parent group.

**Comment by umbe1987** [comment]
The only thing I've noticed is that....it does not work on IE11. Well, yeah, it's just IE....but I also noticed the Basic Example does work, so it is something in this PR. More precisely:

immagine

**Comment by umbe1987** [comment]
> The only thing I've noticed is that....it does not work on IE11.

One way to possibly fix this is to use the filter function in place of find as explained in a comment [here](https://stackoverflow.com/a/37788705/1979665):

This could **probably** be changed like (link to line in [src/ol-layerswitcher.js](https://github.com/dbrnz/ol-layerswitcher/blob/selectable-groups/src/ol-layerswitcher.js#L143)):

e.g. ~~`let baseLyr = lyrs.find(function (l) {`~~ -> `let baseLyr = lyrs.filter()[0](function (l) {`

**Comment by walkermatt** [comment]
@swalterfub thanks for the reminder, I'm wondering if a global option would suffice which determines the group check box behaviour? Open to suggestions as to what the option should be called 😀

**Comment by umbe1987** [comment]
@walkermatt 

> Open to suggestions as to what the option should be called 😀

Something like `checkboxesState`?

**Comment by walkermatt** [comment]
The latest commit adds a `groupSelectStyle` option which can be either:

* `'children'` - *default*, groups have checkboxes which affect child visibility directly
* `'group'` - groups have checkboxes but only group visibility is affected when changed
* `'none'` - the current behaviour, groups do not have checkboxes

As before you can test via the [select-groups example](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/select-groups.html)

**Comment by swalterfub** [comment]
Awesome!

**Comment by umbe1987** [comment]
Could not press thumbs up a hundred times.... thanks, this is cool!

**Comment by dbrnz** [comment]
Great to see this polished up and ready to go! Thanks @walkermatt!!

**Comment by walkermatt** [comment]
I'm currently writing tests and will add docs to README

**Comment by walkermatt** [comment]
This is turning into a bit of an epic! I've now added tests and docs for the `groupSelectStyle`.

* [Example](https://raw.githack.com/dbrnz/ol-layerswitcher/selectable-groups/examples/select-groups.html)
* [Docs](https://github.com/dbrnz/ol-layerswitcher/tree/selectable-groups#layerswitcher)

If you'd like to run the tests you'll have to clone from [dbrnz/ol-layerswitcher/selectable-groups](https://github.com/dbrnz/ol-layerswitcher/tree/selectable-groups).

**Comment by walkermatt** [comment]
I've just cleaned up the commits in another local branch and merged into master. I'll look to release shortly.

**Comment by walkermatt** [comment]
Merged and released as [v3.3.0](https://www.npmjs.com/package/ol-layerswitcher/v/3.3.0) :tada: 

Thanks for everyone's help and patience on this one :smile_cat:

**Comment by Hosaana** [comment]
Hello,
can I have documentation for option groupSelectStyle

Thanks a lot

**Comment by walkermatt** [comment]
@Hosaana see the last item in the [list of options accepted](https://github.com/walkermatt/ol-layerswitcher#layerswitcher).

**Pull request closed without merging**
