### PR TITLE
Modifications to click activation & panel styling

### PR DESCRIPTION
**Pull request by devsupportman**
1. - New option to start with panel open.
2. - Move button outside of panel when using click activation (see examples)
3. - Changes to layer & group name alignment (when wrapping align with beginning of name).
4. - Minor editing to README.md

### CODE REVIEW

**Comment by walkermatt** [comment]
Do you have a link to an example that demonstrates the changes?

**Comment by devsupportman** [comment]
### Alignment changes
Before:
image

After:
image

**Comment by walkermatt** [comment]
Sorry to be a pain, can the format changes could be split out into a separate PR? It's making it very difficult to see the functional changes.

**Comment by devsupportman** [comment]
I've rolled back a couple of changes that were just muddying the water and merged upstream master.

**Comment by walkermatt** [comment]
@devsupportman I've a bunch of tests ready to commit tomorrow morning then I think we're good 👍

There are a few other changes such as improving the names of options and CSS classes but I think we should roll those into the next major version.

**Comment by devsupportman** [comment]
Looks good to me

**Pull request merged**
